// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TableService.Data;

#nullable disable

namespace TableService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TableService.Models.Table", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TableId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TableStart")
                        .HasColumnType("datetime2");

                    b.Property<string>("TableType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TableId");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Price = 100000m,
                            Status = "Available",
                            TableNumber = "Ban 1",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8745),
                            TableType = "VIP"
                        },
                        new
                        {
                            TableId = 2,
                            Price = 80000m,
                            Status = "Available",
                            TableNumber = "Ban 2",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8759),
                            TableType = "Standard"
                        },
                        new
                        {
                            TableId = 3,
                            Price = 100000m,
                            Status = "Occupied",
                            TableNumber = "Ban 3",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8761),
                            TableType = "VIP"
                        },
                        new
                        {
                            TableId = 4,
                            Price = 80000m,
                            Status = "Available",
                            TableNumber = "Ban 4",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8762),
                            TableType = "Standard"
                        },
                        new
                        {
                            TableId = 5,
                            Price = 80000m,
                            Status = "Available",
                            TableNumber = "Ban 5",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8763),
                            TableType = "Standard"
                        },
                        new
                        {
                            TableId = 6,
                            Price = 100000m,
                            Status = "Occupied",
                            TableNumber = "Ban 6",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8766),
                            TableType = "VIP"
                        },
                        new
                        {
                            TableId = 7,
                            Price = 80000m,
                            Status = "Available",
                            TableNumber = "Ban 7",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8768),
                            TableType = "Standard"
                        },
                        new
                        {
                            TableId = 8,
                            Price = 120000m,
                            Status = "Available",
                            TableNumber = "Ban 8",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8769),
                            TableType = "VIP"
                        },
                        new
                        {
                            TableId = 9,
                            Price = 80000m,
                            Status = "Occupied",
                            TableNumber = "Ban 9",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8770),
                            TableType = "Standard"
                        },
                        new
                        {
                            TableId = 10,
                            Price = 120000m,
                            Status = "Available",
                            TableNumber = "Ban 10",
                            TableStart = new DateTime(2024, 10, 27, 3, 56, 46, 303, DateTimeKind.Local).AddTicks(8771),
                            TableType = "VIP"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
